import { MasterclassUpgradeTab } from "./MasterclassUpgradeTab.js";

const ROYAL_ARMORY_UPGRADES = [
    { storageIndex: 30, displayIndex: "S1 #30", name: "Collect Resources Tool", maxLevel: 1 },
    { storageIndex: 46, displayIndex: "S2 #46", name: "Royal Talent Points I", maxLevel: 200 },
    { storageIndex: 58, displayIndex: "S3 #58", name: "Solo Militia Status", maxLevel: 1000 },
    { storageIndex: 31, displayIndex: "S4 #31", name: "Upgrade Outposts Tool", maxLevel: 1 },
    { storageIndex: 9, displayIndex: "S5 #9", name: "Blunder Outpost PTS", maxLevel: 999999 },
    { storageIndex: 41, displayIndex: "S6 #41", name: "Royal Marble", maxLevel: 50 },
    { storageIndex: 70, displayIndex: "S7 #70", name: "Resource Replenish", maxLevel: 1000 },
    { storageIndex: 37, displayIndex: "S8 #37", name: "Parchment of Enchantment", maxLevel: 1 },
    { storageIndex: 78, displayIndex: "S9 #78", name: "Statue Flair", maxLevel: 1 },
    { storageIndex: 35, displayIndex: "S10 #35", name: "Anti-Rodent Power Move I", maxLevel: 999999 },
    { storageIndex: 27, displayIndex: "S11 #27", name: "Trader Profession", maxLevel: 1 },
    { storageIndex: 71, displayIndex: "S12 #71", name: "Trading Rank", maxLevel: 6 },
    { storageIndex: 20, displayIndex: "S13 #20", name: "Tremendous Traders", maxLevel: 999999 },
    { storageIndex: 60, displayIndex: "S14 #60", name: "Blunder Hills Militia", maxLevel: 10 },
    { storageIndex: 32, displayIndex: "S15 #32", name: "Move Units Tool", maxLevel: 1 },
    { storageIndex: 19, displayIndex: "S16 #19", name: "Wonderful Workers", maxLevel: 999999 },
    { storageIndex: 79, displayIndex: "S17 #79", name: "Compounding Outposting", maxLevel: 1 },
    { storageIndex: 2, displayIndex: "S18 #2", name: "Kingdom Expansion 2", maxLevel: 1 },
    { storageIndex: 61, displayIndex: "S19 #61", name: "Yumyum Desert Militia", maxLevel: 10 },
    { storageIndex: 57, displayIndex: "S20 #57", name: "Greater Education", maxLevel: 1 },
    { storageIndex: 23, displayIndex: "S21 #23", name: "Mighty Militia", maxLevel: 999999 },
    { storageIndex: 47, displayIndex: "S22 #47", name: "Royal Talent Points II", maxLevel: 200 },
    { storageIndex: 0, displayIndex: "S23 #0", name: "Resource Grades", maxLevel: 1 },
    { storageIndex: 10, displayIndex: "S24 #10", name: "Yumyum Outpost PTS", maxLevel: 999999 },
    { storageIndex: 80, displayIndex: "S25 #80", name: "Prismatic Guardian", maxLevel: 100 },
    { storageIndex: 28, displayIndex: "S26 #28", name: "Guard Profession", maxLevel: 1 },
    { storageIndex: 21, displayIndex: "S27 #21", name: "Great Guards", maxLevel: 10 },
    { storageIndex: 68, displayIndex: "S28 #68", name: "Kingdom Sovereignty", maxLevel: 36 },
    { storageIndex: 73, displayIndex: "S29 #73", name: "Command Rank", maxLevel: 5 },
    { storageIndex: 24, displayIndex: "S30 #24", name: "Charismatic Commanders", maxLevel: 999999 },
    { storageIndex: 50, displayIndex: "S31 #50", name: "Global Decree - OL", maxLevel: 100 },
    { storageIndex: 56, displayIndex: "S32 #56", name: "Super Talent Unban", maxLevel: 1 },
    { storageIndex: 38, displayIndex: "S33 #38", name: "Parchment Surplus", maxLevel: 999999 },
    { storageIndex: 81, displayIndex: "S34 #81", name: "Weekly Skull Stipend", maxLevel: 100 },
    { storageIndex: 42, displayIndex: "S35 #42", name: "Support Camps", maxLevel: 3 },
    { storageIndex: 43, displayIndex: "S36 #43", name: "Super Support", maxLevel: 100 },
    { storageIndex: 3, displayIndex: "S37 #3", name: "Kingdom Expansion 3", maxLevel: 1 },
    { storageIndex: 62, displayIndex: "S38 #62", name: "Frostbite Tundra Militia", maxLevel: 10 },
    { storageIndex: 18, displayIndex: "S39 #18", name: "Global Decree - RG", maxLevel: 999999 },
    { storageIndex: 11, displayIndex: "S40 #11", name: "Tundra Outpost PTS", maxLevel: 999999 },
    { storageIndex: 52, displayIndex: "S41 #52", name: "Experiential Triumph", maxLevel: 100 },
    { storageIndex: 36, displayIndex: "S42 #36", name: "Anti-Rodent Power Move II", maxLevel: 999999 },
    { storageIndex: 29, displayIndex: "S43 #29", name: "Surveyor Profession", maxLevel: 1 },
    { storageIndex: 72, displayIndex: "S44 #72", name: "Intel Rank", maxLevel: 5 },
    { storageIndex: 22, displayIndex: "S45 #22", name: "Super Surveyors", maxLevel: 999999 },
    { storageIndex: 76, displayIndex: "S46 #76", name: "Farmer Joe", maxLevel: 100 },
    { storageIndex: 44, displayIndex: "S47 #44", name: "Savage Strongholds", maxLevel: 3 },
    { storageIndex: 69, displayIndex: "S48 #69", name: "Super Savagery", maxLevel: 100 },
    { storageIndex: 48, displayIndex: "S49 #48", name: "Royal Talent Points III", maxLevel: 200 },
    { storageIndex: 74, displayIndex: "S50 #74", name: "Military Rank", maxLevel: 5 },
    { storageIndex: 25, displayIndex: "S51 #25", name: "Kingsman Knights", maxLevel: 999999 },
    { storageIndex: 17, displayIndex: "S52 #17", name: "Peacetime Milita", maxLevel: 1 },
    { storageIndex: 33, displayIndex: "S53 #33", name: "Rat Breeding Protocol I", maxLevel: 10 },
    { storageIndex: 39, displayIndex: "S54 #39", name: "Parchment Doubleprint", maxLevel: 100 },
    { storageIndex: 4, displayIndex: "S55 #4", name: "Kingdom Expansion 4", maxLevel: 1 },
    { storageIndex: 63, displayIndex: "S56 #63", name: "Hyperion Nebula Militia", maxLevel: 10 },
    { storageIndex: 12, displayIndex: "S57 #12", name: "Hyperion Outpost PTS", maxLevel: 999999 },
    { storageIndex: 75, displayIndex: "S58 #75", name: "Purity Rank", maxLevel: 1 },
    { storageIndex: 26, displayIndex: "S59 #26", name: "Passionate Priests", maxLevel: 999999 },
    { storageIndex: 77, displayIndex: "S60 #77", name: "State-Wide Propoganda", maxLevel: 100 },
    { storageIndex: 53, displayIndex: "S61 #53", name: "Tip-Top 'sources", maxLevel: 10 },
    { storageIndex: 49, displayIndex: "S62 #49", name: "Royal Talent Points IV", maxLevel: 200 },
    { storageIndex: 40, displayIndex: "S63 #40", name: "Parchment Recycling", maxLevel: 50 },
    { storageIndex: 1, displayIndex: "S64 #1", name: "Perfect Purification", maxLevel: 300 },
    { storageIndex: 51, displayIndex: "S65 #51", name: "Global Decree - PM", maxLevel: 40 },
    { storageIndex: 82, displayIndex: "S66 #82", name: "Ribbonic Guardian", maxLevel: 20 },
    { storageIndex: 59, displayIndex: "S67 #59", name: "Orblet Pittance", maxLevel: 100 },
    { storageIndex: 45, displayIndex: "S68 #45", name: "Royal Reverence", maxLevel: 20 },
    { storageIndex: 55, displayIndex: "S69 #55", name: "Talent Reattainment", maxLevel: 300 },
];

const royalResourceIcon = (resourceId) => `/assets/royal-resources/RGres${resourceId}.png`;

const resourceFields = (world, resourceIds) =>
    resourceIds.map((resourceId) => ({
        key: `royalResource${resourceId}`,
        path: `RoyalG[1][${resourceId}]`,
        name: `RGres${resourceId}`,
        iconUrl: royalResourceIcon(resourceId),
    }));

const ROYAL_ARMORY_RESOURCE_TABS = [
    { world: 1, resourceIds: [0, 1, 2, 3, 4, 5] },
    { world: 2, resourceIds: [10, 11, 12, 13, 14, 15] },
    { world: 3, resourceIds: [20, 21, 22, 23, 24, 25, 26] },
    { world: 4, resourceIds: [30, 31, 32, 33, 34, 35, 36, 37] },
    { world: 5, resourceIds: [40, 41, 42, 43, 44, 45, 46, 47] },
    { world: 6, resourceIds: [50, 51, 52, 53, 54, 55, 56, 57] },
    { world: 7, resourceIds: [60, 61, 62, 63, 64, 65, 66, 67] },
].map(({ world, resourceIds }) => ({
    id: `w${world}`,
    label: `W${world}`,
    fields: resourceFields(world, resourceIds),
}));

export const RoyalArmoryTab = () =>
    MasterclassUpgradeTab({
        title: "ROYAL ARMORY",
        description: "Manage Royal Guard Royal Armory upgrades.",
        levelsPath: "RoyalG[2]",
        staticUpgrades: ROYAL_ARMORY_UPGRADES,
        currencyTitle: "ROYAL RESOURCES",
        currencyTabs: ROYAL_ARMORY_RESOURCE_TABS,
        fallbackPrefix: "Royal Armory Upgrade",
    });
